### PR TITLE
fix(types): unwrap refs in `mapWritableState` for setup stores

### LINKED ISSUE #2804: `mapWritableState` on setup stores doesn't unwrap refs
### Reproduction

https://play.pinia.vuejs.org/#eNqVVc2O2jAQfhUrl6VacKC0WwnBim21h+2hrUrVHpoeQjKAdx07sicsEuLdO3GAmBAqKvETz8/n+WYmM9vgIc/5uoBgFIxtYkSOTMZqOYkCtFFwHymR5dog27Iszn8ZgfFcwgxjBLZjC6MzdpMLJeIbz7Kw8EnTwQoUWj3kYoba1PY8THShEEwvqa16cS442gbM17zU2X9A6Mqido8UbBxACou4kAQUKcbSGOMR67xhk3vWcRLGcMRUIWV52L3pln9lPAVCOqqcGOOcN2l32tl12e8bF9Op7uZPhXwRqsHwCFPLCcKF6HAywJVO7TFAoRIDGSgkansRw5WwXN3eVsedc44UfcZhVWGqKh0QslxSFHRibDwvELVi00SK5IWq38KF3U7YgHri6XAn5evMaBxWSHtUw8Lr8SesT/AzaAVmqFn/FD0V6/ufsSyA6UWrS49tt62K3W4clt7XBFlX4kICaoP/Iu/hNoh7mmtIe+Y1YU9Ykx2HXtGDblC9aj3qS/5staIZ4Hoo2itoABwbLQrca15KoiB0zxxs1psb/WrBkH8U7Ds9CqY0UMIU1qi1dK9m5bZCzO0oDJNUkX0KUqwNV4ChyrPwzGd6x+/4IJRiHtJFoVApbE6vIY9eCtk16AfTaZ8P3vEPDnU93INmTdRrwzWUaJERss6mQ/6eD95Soi368stJKgFIuKYhZoDiMGCuvbfhdnJ3Q3d2/2EcUPnRJlotxLJR/HIKCglm30InTRBLqV8/OxmaAo5kkhUkLy3yZ7upSH0z4CLzEoCxWQJW6sfZF9jQ81GZ6bSQ+0JcUH4Hq2VRxliZfSxUSmF7di7aJ9fLQi1/2McNgrIHUmWg9WR1BSnHxCXqdbhDPvSyeHmZUUqPy4y2kVA09v0tdrY4DSyOSorG32ZUKYuXNuvEh+9UCwRMYxN19+vPEarg2ocwRdHp084p7QxgYRSF1jpFKQFk5+XgdBtfyd/QVfRtEm3u/naS3p7sEjXCYcyWy9Xb9k5Ycj6ZiyMauk5DHOi/+g12fwHukSVW

### Steps to reproduce the bug

- see template

### Expected behavior

no type error

### Actual behavior

type error

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jh-leong**
close #2804

### CODE REVIEW

**Comment by noootwo** [comment]
@posva When is this PR scheduled to be merged?

File: packages/pinia/src/types.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ import { Pinia } from './rootStore'
 /**
  * Generic state of a Store
  */
-export type StateTree = Record<string | number | symbol, any>
+export type StateTree = Record<PropertyKey, any>
```
Comment (posva) [inline packages/pinia/src/types.ts:14]: TIL!

**Review by posva — APPROVED** [review]
Thanks! I wanted to remove the redundancy with `SS` so I used `UnwrapRef` like `Store` does to correctly extract the final type.
