### PR TITLE
fix(nuxt): plugin injection on latest Nuxt 3 context

### LINKED ISSUE #1428: Nux3 - inject is not a function
### Reproduction

none

### Steps to reproduce the bug

package.json

```{
  "private": true,
  "scripts": {
    "dev": "nuxi dev --https --ssl-cert ../certs/example.com+5.pem --ssl-key ../certs/example.com+5-key.pem",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@iconify/json": "^2.1.73",
    "@unocss/nuxt": "^0.43.2",
    "@vueuse/core": "^8.9.0",
    "@vueuse/nuxt": "^8.9.0",
    "nuxt": "npm:nuxt3@latest",
    "sass": "^1.53.0"
  },
  "dependencies": {
    "@inkline/inkline": "^3.0.9",
    "@inkline/nuxt": "3.1.4",
    "@pinia/nuxt": "^0.1.9",
    "@vueuse/integrations": "^8.9.0",
    "nuxt-graphql-client": "^0.0.33",
    "pinia": "^2.0.14"
  }
}
```

### Expected behavior

run Pinia in Nuxt3

### Actual behavior

```
[nuxt] [request error] inject is not a function
  at PiniaNuxtPlugin (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:30966:3)      
  at fn (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:571:27)
  at Object.callAsync (/C:/Work/xxx/Website/Code/xxx/Frontend/node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:573:23)
  at applyPlugin (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:540:29)
  at Module.applyPlugins (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:550:11)
  at async createNuxtAppServer (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:46:7)
  at async Object.renderToString (/C:/Work/xxx/Website/Code/xxx/Frontend/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)       
  at async /C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dev/index.mjs:473:20
  at async /C:/Work/xxx/Website/Code/xxx/Frontend/node_modules/h3/dist/index.mjs:420:19     ```

### Additional information

Hi,

Sorry for nor providing repro, but so far I cannot get any errors when I try it on Stackblitz. So it must be something in my project.

Basicall I follow those steps:
1. `yarn add pinia @pinia/nuxt` - im on Nuxt3
2. add `modules: ['@pinia/nuxt']` in nuxt.config.ts
3. Then Immediately I get the error. If I remove Pinia from modules, Its back to normal.

Any clues what might be going on?

Thank you

### LINKED ISSUE #1432: inject is not a function PiniaNuxtPlugin
### Reproduction

https://stackblitz.com/edit/github-1xxy9u?file=package.json

### Steps to reproduce the bug
inject is not a function PiniaNuxtPlugin
Getting error on nuxt v3.0.0-rc.4-27620285.c95a48c update

### Expected behavior

Works as expected like previus version

### Actual behavior

Require update

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brownsugar**
As Nuxt 3 removed the legacy context (https://github.com/nuxt/framework/pull/5630), the `inject` argument and `nuxtState` option is not available anymore.

Fixes #1428
fix #1432

### CODE REVIEW

**Comment by posva** [comment]
Thanks, I will take a look. I think we will also need to migrate to nuxt/kit. It was removed in the past due to some missing features but it should be ready now

**Comment by pi0** [comment]
Nuxt kit is now stable to migrate to but buntime part (of plugins) can be upgraded to bridge. Kit utils are only for module/build level not runtime.

**Review by msonowal — APPROVED** [review]

File: packages/nuxt/src/templates/plugin.ts [hunk 1]
```diff
@@ -43,10 +48,14 @@ const PiniaNuxtPlugin: Plugin = (context, inject) => {
       })
     } else {
       // there is no beforeNuxtRender in Nuxt 3
-      context.nuxtState.pinia = pinia.state.value
+      // @ts-expect-error: vue 3 only
+      context.ssrContext.payload.data.pinia = pinia.state.value
```
Comment (posva) [inline packages/nuxt/src/templates/plugin.ts]:
```suggestion
      context.ssrContext.payload.pinia = pinia.state.value
```

File: packages/nuxt/src/templates/plugin.ts [hunk 2]
```diff
@@ -43,10 +48,14 @@ const PiniaNuxtPlugin: Plugin = (context, inject) => {
...
+    }
+  } else {
+    const source = isVue2 ? context.nuxtState : context.payload.data
```
Comment (posva) [inline packages/nuxt/src/templates/plugin.ts]:
```suggestion
    const source = isVue2 ? context.nuxtState : context.payload
```

**Review by posva — APPROVED** [review]
Thanks. Let's go with this for the moment as it works with Nuxt2,3 and bridge

**Comment by msonowal** [comment]
@posva  will you tag new version?

File: packages/nuxt/src/templates/plugin.ts [hunk 3]
```diff
@@ -43,10 +48,14 @@ const PiniaNuxtPlugin: Plugin = (context, inject) => {
       })
     } else {
       // there is no beforeNuxtRender in Nuxt 3
-      context.nuxtState.pinia = pinia.state.value
+      // @ts-expect-error: vue 3 only
+      context.ssrContext.payload.pinia = pinia.state.value
+    }
+  } else {
+    const source = isVue2 ? context.nuxtState : context.payload
```
Comment (posva) [inline packages/nuxt/src/templates/plugin.ts:55]: Was this change necessary? 🤔 
It created other problems: https://github.com/vuejs/pinia/issues/1447

Comment (brownsugar) [reply packages/nuxt/src/templates/plugin.ts:55]: Because nuxtState is removed in Nuxt 3 https://github.com/nuxt/framework/pull/5630

It's weird that I didn't get error when set `ssr: false`.

Comment (posva) [reply packages/nuxt/src/templates/plugin.ts:55]: ok, thanks

**Comment by nathanchase** [comment]
In Nuxt 3, I can get to `$auth` ([auth module](https://github.com/Teranode/nuxt-module-alternatives/tree/master/%40nuxtjs-alt/auth)) by way of `useNuxtApp()` in components and composables, but how would you access it in a Pinia store?

In components, I usually just do:
```js
const nuxtApp = useNuxtApp();
const authUser = nuxtApp.$auth.user;
```
but in a `stores/store.ts`, `useNuxtApp` is not available, so I'm not quite sure how to get to the context?
```
[nuxt] [request error] nuxt instance unavailable
  at Module.useNuxtApp (./.nuxt/dist/server/server.mjs:520:13)
  at $id_C1ltjrBOrk (./.nuxt/dist/server/server.mjs:10547:39)
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:32909:3)
```

Is this issue the reason - change in context access?

Reference: https://github.com/Teranode/nuxt-module-alternatives/discussions/54
