### PR TITLE
fix(types): setupStore getter types (#1430)

### LINKED ISSUE #1430: Typescript type of getter in composed store is wrong
### Reproduction

https://github.com/DerZade/pinia-bug-report

### Steps to reproduce the bug

Open the `App.vue` in VS Code or any other editor, that supports typescript type-checking IntelliSense. `counter.nPlusX` is inferred as type `number`, although it actually is a `(x: number) => number`.

### Expected behavior

A computed property of a composed store, that returns a function (to achieve [the effect of a getter, to which I can pass arguments](https://pinia.vuejs.org/core-concepts/getters.html#passing-arguments-to-getters)) should have a correctly inferred Typescript type.

### Actual behavior

A computed property of a composed store, that returns a function, has a inferred type of the return type of said function.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Derhelios66**
I have an Idea to fix the following Issue. :smile:
Fix https://github.com/vuejs/pinia/issues/1430

### CODE REVIEW

File: packages/pinia/src/types.ts [hunk 1]
```diff
@@ -601,7 +601,7 @@ export type _ExtractActionsFromSetupStore<SS> = SS extends undefined | void
 export type _ExtractGettersFromSetupStore<SS> = SS extends undefined | void
   ? {}
   : _ExtractGettersFromSetupStore_Keys<SS> extends keyof SS
-  ? _UnwrapAll<Pick<SS, _ExtractGettersFromSetupStore_Keys<SS>>>
```
Comment (posva) [inline packages/pinia/src/types.ts:604]: I need to check if removing this also breaks the <kbd>ctrl</kbd> + click in IDEs

**Comment by Derhelios66** [comment]
Dont worry i've just rebased the branch 😄

**Comment by bodograumann** [comment]
I had to update my mock wrapper after updating to 2.0.17 by adding `UnwrapRef` to the getters:
```typescript
type Mocked<T> = { [P in keyof T]: ReturnType<typeof jest.fn> };
function mocked<Id extends string, S, G, A>(store: Store<Id, S, G, A>): S & UnwrapRef<G> & Mocked<A> {
  /* eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the new type is due to `app.use(createTestingPinia())` */
  //@ts-ignore
  return store;
}
```

`G` was previously inferred as having plain properties, but now it somehow contains `ComputedRef`s.
I hope that this info might help others.
